name: Bug Report
description: File a bug report to help improve gotailwind
title: "[Bug]: "
labels: [bug]
assignees:
  - hookenz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please complete the form below so we can help troubleshoot the issue.

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go version go1.22.0 linux/amd64
    validations:
      required: true

  - type: textarea
    id: go-env
    attributes:
      label: Output of `go env`
      description: Please paste the full output of `go env`
      render: shell
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you're experiencing.
      placeholder: What did you do? What did you expect to happen? What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Run command '...'
        2. Create file '...'
        3. Observe output
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Output
      description: Paste any error messages or logs here.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      description: Please confirm you’ve done the following
      options:
        - label: I have searched [existing issues](https://github.com/hookenz/gotailwind/issues) to avoid duplicates.
          required: true
        - label: I have provided the required Go environment information.
          required: true
